### ISSUE TITLE
how much?

### ISSUE THREAD

**Issue by Muse30** [rexyrexy/PortAIO-Reborn#4]
hi im nub coding so I want to buy AIO how much?

**Comment by SnowDenix** [comment]
1 million dolar for ezevade script ezpz

**Comment by rexyrexy** [comment]
Selling it for 15 dollar.. :D

**Comment by Muse30** [comment]
good luck

**Comment by rexyrexy** [comment]
Thank you :D

**Comment by Monnq** [comment]
what yo do if mi chergback?

**Comment by rexyrexy** [comment]
I will prove my self to Paypal support for I'm right with :100: right

Closed..
