### ISSUE TITLE
Menu not fully loading 

### ISSUE THREAD

**Issue by lgndz** [rexyrexy/PortAIO-Reborn#6]
Script injects correctly
Loads intro chat
Does not display the menu for the appropriately selected addons (under portAIO-Reborn) - for example, you can select OKTW or iDZezreal but neither actually seem to load the assembly (no logic on any mode - just basic orb)

**Comment by berbb** [comment]
https://github.com/Muse30/PortAIO

**Comment by lgndz** [comment]
??

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Mon, May 16, 2016 at 9:22 PM -0700, "berbb" <notifications@github.com> wrote:












https://github.com/Muse30/PortAIO

**Comment by rexyrexy** [comment]
I will fix it it's was a problem of my github when i'm pushing the commit sorry..
